service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  timeout: 60 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):348002133723-d56dg9813ssnghu4nft97h8t38fd4d6l.apps.googleusercontent.com}
    CLIENT_SECRET: ${file(config.json):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}
    PROJECT_ID: ${file(config.json):meet-app-370819}
    CALENDAR_ID: ${file(config.json):fullstackwebdev@careerfoundry.com}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get